package com.mycompany.maven_exam;

import static com.google.common.io.Files.getFileExtension;
import java.awt.Color;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Амина
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFrame() {
        initComponents();
        FreqTable.getTableHeader().setForeground(Color.blue);
        FreqTable.getTableHeader().setBackground(Color.cyan);
    }

    ArrayList<String> text;
    ArrayList<String> changed_text;
    ArrayList<String> ru_stop_words;
    ArrayList<String> eng_stop_words;
    
    DefaultTableModel freq_table;
    FileWork fileWorker;
    TextWork textWorker;
    AnalysisWork analyst;
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guideDialog = new javax.swing.JDialog();
        guidePanel = new javax.swing.JPanel();
        exitFromGuideButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        MainJFrame = new javax.swing.JFrame();
        mainPanel = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        FreqTable = new javax.swing.JTable();
        numberDelWordsField = new javax.swing.JLabel();
        popularWordField = new javax.swing.JLabel();
        unpopularWordField = new javax.swing.JLabel();
        numberWordsField = new javax.swing.JLabel();
        guideButton = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        importButton = new javax.swing.JMenuItem();
        analyzeButton = new javax.swing.JMenuItem();
        exportButton = new javax.swing.JMenuItem();
        exitButton = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        useStopWords = new javax.swing.JMenu();
        useRuStopWordsButton = new javax.swing.JCheckBoxMenuItem();
        editRuStopWordsButton = new javax.swing.JMenuItem();
        useEngStopWordsButton = new javax.swing.JCheckBoxMenuItem();
        editEngStopWordsButton = new javax.swing.JMenuItem();
        extraSettingsMenu = new javax.swing.JMenu();
        useEngButton = new javax.swing.JRadioButtonMenuItem();
        useRusButton = new javax.swing.JRadioButtonMenuItem();
        deleteSelectionsButton = new javax.swing.JMenuItem();
        saveReportMessage = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        okSaveReportButton = new javax.swing.JButton();
        uploadStopWordsMessage = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        okUploadStopWordsButton = new javax.swing.JButton();
        uploadFileMessage = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        okUploadFileButton = new javax.swing.JButton();
        loadingFrame = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        gifLabel = new javax.swing.JLabel();
        group = new javax.swing.ButtonGroup();
        ruStopWordsFrame = new javax.swing.JFrame();
        ruStopWordsScrollPanel = new javax.swing.JScrollPane();
        ruStopWordsList = new javax.swing.JList<>();
        engStopWordsFrame = new javax.swing.JFrame();
        engStopWordsScrollPanel = new javax.swing.JScrollPane();
        engStopWordsList = new javax.swing.JList<>();
        startPanel = new javax.swing.JPanel();
        helloLabel1 = new javax.swing.JLabel();
        helloLabel2 = new javax.swing.JLabel();
        descriptionLabel1 = new javax.swing.JLabel();
        descriptionLabel2 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        descriptionLabel3 = new javax.swing.JLabel();

        guidePanel.setBackground(new java.awt.Color(255, 255, 255));

        exitFromGuideButton.setBackground(new java.awt.Color(204, 204, 204));
        exitFromGuideButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exitFromGuideButton.setText("Ок");
        exitFromGuideButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitFromGuideButton.setFocusPainted(false);
        exitFromGuideButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitFromGuideButton.setPreferredSize(new java.awt.Dimension(25, 25));
        exitFromGuideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFromGuideButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Инструкция по использованию");

        jLabel2.setText("1. В главном меню \"Файл\" нажмите кнопку \"Загрузить файл\" и загрузите файл формата txt для анализа.");

        jLabel3.setText("2. В меню \"Настройки\" можно применить фильтр для очистки текста от стоп-слов, ");

        jLabel4.setText("а в расширенных настройках есть функция использования только русского или английского языка. ");

        jLabel5.setText("Если вы хотите применить удаление стоп-слов, то загрузите файл со стоп-словами как в пункте 1.");

        jLabel6.setText("3. Нажмите кнопку \"Провести анализ\". В результате появится таблица со списком слов и их частотами и ");

        jLabel7.setText("основная информация о выполненном анализе текста.");

        jLabel8.setText("выбрав опцию \"Использовать стоп-слова\" для удаления лишних слов из текста,");

        jLabel10.setText("4. Нажмите кнопку \"Сохранить отчет\", если вы хотите сохранить выполненный анализ текст. ");

        jLabel15.setText("Также нажав кнопку \"Редактировать стоп-слова\", вы можете выделить стоп-слова, которые");

        jLabel16.setText("не будут учитываться при фильтрации текста.");

        javax.swing.GroupLayout guidePanelLayout = new javax.swing.GroupLayout(guidePanel);
        guidePanel.setLayout(guidePanelLayout);
        guidePanelLayout.setHorizontalGroup(
            guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guidePanelLayout.createSequentialGroup()
                .addGroup(guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guidePanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1))
                    .addGroup(guidePanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guidePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitFromGuideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(guidePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(guidePanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(guidePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        guidePanelLayout.setVerticalGroup(
            guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guidePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitFromGuideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout guideDialogLayout = new javax.swing.GroupLayout(guideDialog.getContentPane());
        guideDialog.getContentPane().setLayout(guideDialogLayout);
        guideDialogLayout.setHorizontalGroup(
            guideDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        guideDialogLayout.setVerticalGroup(
            guideDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MainJFrame.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        FreqTable.setBackground(new java.awt.Color(204, 255, 255));
        FreqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Слово", "Частота"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel.setViewportView(FreqTable);

        guideButton.setBackground(new java.awt.Color(204, 204, 204));
        guideButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        guideButton.setText("?");
        guideButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guideButton.setFocusPainted(false);
        guideButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guideButton.setPreferredSize(new java.awt.Dimension(30, 30));
        guideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unpopularWordField, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(popularWordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(guideButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numberDelWordsField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberWordsField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(numberWordsField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numberDelWordsField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(popularWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(unpopularWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guideButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)))
                .addContainerGap())
        );

        menu.setBackground(new java.awt.Color(204, 204, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        menu.setPreferredSize(new java.awt.Dimension(95, 35));

        mainMenu.setBackground(new java.awt.Color(204, 204, 255));
        mainMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainMenu.setForeground(new java.awt.Color(102, 102, 255));
        mainMenu.setText("Файл");
        mainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        importButton.setForeground(new java.awt.Color(102, 102, 255));
        importButton.setText("Загрузить файл");
        importButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });
        mainMenu.add(importButton);

        analyzeButton.setForeground(new java.awt.Color(102, 102, 255));
        analyzeButton.setText("Провести анализ");
        analyzeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        analyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButtonActionPerformed(evt);
            }
        });
        mainMenu.add(analyzeButton);

        exportButton.setForeground(new java.awt.Color(102, 102, 255));
        exportButton.setText("Сохранить отчет");
        exportButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });
        mainMenu.add(exportButton);

        exitButton.setForeground(new java.awt.Color(102, 102, 255));
        exitButton.setText("Выход");
        exitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        mainMenu.add(exitButton);

        menu.add(mainMenu);

        settingsMenu.setBackground(new java.awt.Color(204, 204, 255));
        settingsMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        settingsMenu.setForeground(new java.awt.Color(102, 102, 255));
        settingsMenu.setText("Настройки");
        settingsMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        useStopWords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        useStopWords.setForeground(new java.awt.Color(102, 102, 255));
        useStopWords.setText("Использовать стоп-слова");

        useRuStopWordsButton.setForeground(new java.awt.Color(102, 102, 255));
        useRuStopWordsButton.setText("Русские стоп-слова");
        useRuStopWordsButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        useRuStopWordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useRuStopWordsButtonActionPerformed(evt);
            }
        });
        useStopWords.add(useRuStopWordsButton);

        editRuStopWordsButton.setForeground(new java.awt.Color(102, 102, 255));
        editRuStopWordsButton.setText("Редактировать русские стоп-слова");
        editRuStopWordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRuStopWordsButtonActionPerformed(evt);
            }
        });
        useStopWords.add(editRuStopWordsButton);

        useEngStopWordsButton.setForeground(new java.awt.Color(102, 102, 255));
        useEngStopWordsButton.setText("Английские стоп-слова");
        useEngStopWordsButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        useEngStopWordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useEngStopWordsButtonActionPerformed(evt);
            }
        });
        useStopWords.add(useEngStopWordsButton);

        editEngStopWordsButton.setForeground(new java.awt.Color(102, 102, 255));
        editEngStopWordsButton.setText("Редактировать английские стоп-слова");
        editEngStopWordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEngStopWordsButtonActionPerformed(evt);
            }
        });
        useStopWords.add(editEngStopWordsButton);

        settingsMenu.add(useStopWords);

        extraSettingsMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        extraSettingsMenu.setForeground(new java.awt.Color(102, 102, 255));
        extraSettingsMenu.setText("Расширенные настройки");

        group.add(useEngButton);
        useEngButton.setForeground(new java.awt.Color(102, 102, 255));
        useEngButton.setText("Очистить русский язык");
        useEngButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        extraSettingsMenu.add(useEngButton);

        group.add(useRusButton);
        useRusButton.setForeground(new java.awt.Color(102, 102, 255));
        useRusButton.setText("Очистить английский язык");
        useRusButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        extraSettingsMenu.add(useRusButton);

        deleteSelectionsButton.setForeground(new java.awt.Color(102, 102, 255));
        deleteSelectionsButton.setText("Отменить выбор");
        deleteSelectionsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteSelectionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectionsButtonActionPerformed(evt);
            }
        });
        extraSettingsMenu.add(deleteSelectionsButton);

        settingsMenu.add(extraSettingsMenu);

        menu.add(settingsMenu);

        MainJFrame.setJMenuBar(menu);

        javax.swing.GroupLayout MainJFrameLayout = new javax.swing.GroupLayout(MainJFrame.getContentPane());
        MainJFrame.getContentPane().setLayout(MainJFrameLayout);
        MainJFrameLayout.setHorizontalGroup(
            MainJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainJFrameLayout.setVerticalGroup(
            MainJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        saveReportMessage.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setText("Отчет сохранен!");

        okSaveReportButton.setBackground(new java.awt.Color(204, 204, 204));
        okSaveReportButton.setText("Ок");
        okSaveReportButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        okSaveReportButton.setFocusPainted(false);
        okSaveReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okSaveReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(okSaveReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(okSaveReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout saveReportMessageLayout = new javax.swing.GroupLayout(saveReportMessage.getContentPane());
        saveReportMessage.getContentPane().setLayout(saveReportMessageLayout);
        saveReportMessageLayout.setHorizontalGroup(
            saveReportMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        saveReportMessageLayout.setVerticalGroup(
            saveReportMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        uploadStopWordsMessage.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("Файл со стоп-словами загружен!");

        okUploadStopWordsButton.setBackground(new java.awt.Color(204, 204, 204));
        okUploadStopWordsButton.setText("Ок");
        okUploadStopWordsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        okUploadStopWordsButton.setFocusPainted(false);
        okUploadStopWordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okUploadStopWordsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(okUploadStopWordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(okUploadStopWordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout uploadStopWordsMessageLayout = new javax.swing.GroupLayout(uploadStopWordsMessage.getContentPane());
        uploadStopWordsMessage.getContentPane().setLayout(uploadStopWordsMessageLayout);
        uploadStopWordsMessageLayout.setHorizontalGroup(
            uploadStopWordsMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        uploadStopWordsMessageLayout.setVerticalGroup(
            uploadStopWordsMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        uploadFileMessage.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setText("Файл для анализа загружен!");

        okUploadFileButton.setBackground(new java.awt.Color(204, 204, 204));
        okUploadFileButton.setText("Ок");
        okUploadFileButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        okUploadFileButton.setFocusPainted(false);
        okUploadFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okUploadFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(okUploadFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel13)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(okUploadFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout uploadFileMessageLayout = new javax.swing.GroupLayout(uploadFileMessage.getContentPane());
        uploadFileMessage.getContentPane().setLayout(uploadFileMessageLayout);
        uploadFileMessageLayout.setHorizontalGroup(
            uploadFileMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        uploadFileMessageLayout.setVerticalGroup(
            uploadFileMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loadingFrame.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("Проводится анализ текста...");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 255));
        jLabel14.setText("Пожалуйста, подождите!");

        gifLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(gifLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(gifLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout loadingFrameLayout = new javax.swing.GroupLayout(loadingFrame.getContentPane());
        loadingFrame.getContentPane().setLayout(loadingFrameLayout);
        loadingFrameLayout.setHorizontalGroup(
            loadingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loadingFrameLayout.setVerticalGroup(
            loadingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ruStopWordsScrollPanel.setViewportView(ruStopWordsList);

        javax.swing.GroupLayout ruStopWordsFrameLayout = new javax.swing.GroupLayout(ruStopWordsFrame.getContentPane());
        ruStopWordsFrame.getContentPane().setLayout(ruStopWordsFrameLayout);
        ruStopWordsFrameLayout.setHorizontalGroup(
            ruStopWordsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ruStopWordsScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        ruStopWordsFrameLayout.setVerticalGroup(
            ruStopWordsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ruStopWordsScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        engStopWordsScrollPanel.setViewportView(engStopWordsList);

        javax.swing.GroupLayout engStopWordsFrameLayout = new javax.swing.GroupLayout(engStopWordsFrame.getContentPane());
        engStopWordsFrame.getContentPane().setLayout(engStopWordsFrameLayout);
        engStopWordsFrameLayout.setHorizontalGroup(
            engStopWordsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(engStopWordsScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        engStopWordsFrameLayout.setVerticalGroup(
            engStopWordsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(engStopWordsScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        startPanel.setBackground(new java.awt.Color(255, 255, 255));

        helloLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        helloLabel1.setForeground(new java.awt.Color(102, 51, 255));
        helloLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helloLabel1.setText("Добро пожаловать");
        helloLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        helloLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        helloLabel2.setForeground(new java.awt.Color(102, 51, 255));
        helloLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helloLabel2.setText("в программу для анализа текста!");
        helloLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        helloLabel2.setInheritsPopupMenu(false);

        descriptionLabel1.setText("Программа поможет Вам узнать частотность каждого слова в тексте.");

        descriptionLabel2.setText("С помощью неё вы узнаете, количество слов в тексте, какие слова встречаются чаще и реже всего,");

        startButton.setBackground(new java.awt.Color(204, 204, 255));
        startButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startButton.setText("Начать");
        startButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startButton.setFocusPainted(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        descriptionLabel3.setText("и сможете сохранить сделанный отчет.");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(helloLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descriptionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionLabel2)
                            .addComponent(descriptionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(helloLabel2))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(helloLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helloLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(descriptionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel3)
                .addGap(20, 20, 20)
                .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitFromGuideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFromGuideButtonActionPerformed
        guideDialog.dispose();
    }//GEN-LAST:event_exitFromGuideButtonActionPerformed

    private void guideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideButtonActionPerformed
        guideDialog.setVisible(true);
        guideDialog.setBounds(300, 200, 660, 390);
    }//GEN-LAST:event_guideButtonActionPerformed

    private void useRuStopWordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useRuStopWordsButtonActionPerformed
        if(useRuStopWordsButton.getState() && ru_stop_words == null)
        {
            JOptionPane.showMessageDialog (null, "Вы не выбрали файл со стоп-словами!", "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_useRuStopWordsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        fileWorker = new FileWork();
        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Выбор папки");
        filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        filechooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int showDialog = filechooser.showDialog(this, "Выбрать");
        if(showDialog == JFileChooser.APPROVE_OPTION)
        {
            String selectedFile = filechooser.getSelectedFile().toString(); 
            freq_table = (DefaultTableModel) FreqTable.getModel();
            fileWorker.ExportResults(selectedFile, freq_table, numberWordsField, numberDelWordsField, popularWordField, unpopularWordField);            
            
            saveReportMessage.setVisible(true);
            saveReportMessage.setBounds(300,300,200,150);
        } else if(showDialog == JFileChooser.CANCEL_OPTION)
        {
            filechooser.setVisible(false);
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    private void analyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed
        analyst = new AnalysisWork();
        textWorker = new TextWork();
        try{
            changed_text = new ArrayList<>();
            changed_text = textWorker.changeText(text, ru_stop_words, eng_stop_words, useRusButton, useEngButton, useRuStopWordsButton, useEngStopWordsButton, ruStopWordsList, engStopWordsList);
            if(!changed_text.isEmpty())
            {
                loadingFrame.setVisible(true);
                loadingFrame.setBounds(300, 300, 350, 330);
                ImageIcon gif = new ImageIcon(System.getProperty("user.dir")+"/resources/loading.gif");
                gifLabel.setIcon(gif);
            
                timer.setRepeats(false);
                timer.start();
                
                analyst.analyzeProcess(text, changed_text, FreqTable, freq_table, numberWordsField, numberDelWordsField, popularWordField, unpopularWordField);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Вы удалили все слова!", "Oшибка", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog (null, "Ошибка при анализе текста!", "Oшибка", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_analyzeButtonActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        fileWorker = new FileWork();
        textWorker = new TextWork();
        
        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Выбор файлов");
        filechooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int showDialog = filechooser.showDialog(this, "Выбрать");
        if(showDialog == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = filechooser.getSelectedFile();
            String extension = getFileExtension(selectedFile.toString());
            if(selectedFile.getName().equals("stop-ru.txt"))
            {
                ru_stop_words = fileWorker.importFile(selectedFile.toString());
                
                textWorker.uploadStopWords(ru_stop_words, ruStopWordsList, uploadStopWordsMessage, useRuStopWordsButton);
            } else if(selectedFile.getName().equals("stop-eng.txt"))
            {
                eng_stop_words = fileWorker.importFile(selectedFile.toString());
                
                textWorker.uploadStopWords(eng_stop_words, engStopWordsList, uploadStopWordsMessage, useEngStopWordsButton);
            } else if(extension.equals("txt"))
            {
                text = fileWorker.importFile(selectedFile.toString());
                
                uploadFileMessage.setVisible(true);
                uploadFileMessage.setBounds(300,300,230,150);
            } else
            {
                JOptionPane.showMessageDialog (null, "Неверное расширение файла! Выберите файл txt", "Oшибка", JOptionPane.ERROR_MESSAGE);
            }
        } else if(showDialog == JFileChooser.CANCEL_OPTION)
        {
            filechooser.setVisible(false);
        }
    }//GEN-LAST:event_importButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        MainJFrame.setVisible(true);
        MainJFrame.setBounds(200, 100, 850, 700);
        JComponent comp = (JComponent) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor(comp);
        win.dispose();
    }//GEN-LAST:event_startButtonActionPerformed

    private void okSaveReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okSaveReportButtonActionPerformed
        saveReportMessage.dispose();
    }//GEN-LAST:event_okSaveReportButtonActionPerformed

    private void okUploadStopWordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okUploadStopWordsButtonActionPerformed
        uploadStopWordsMessage.dispose();
    }//GEN-LAST:event_okUploadStopWordsButtonActionPerformed

    private void okUploadFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okUploadFileButtonActionPerformed
        uploadFileMessage.dispose();
    }//GEN-LAST:event_okUploadFileButtonActionPerformed

    private void useEngStopWordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useEngStopWordsButtonActionPerformed
        if(useEngStopWordsButton.getState() && eng_stop_words == null)
        {
            JOptionPane.showMessageDialog (null, "Вы не выбрали файл со стоп-словами!", "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_useEngStopWordsButtonActionPerformed

    private void deleteSelectionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectionsButtonActionPerformed
        group.clearSelection();
    }//GEN-LAST:event_deleteSelectionsButtonActionPerformed

    private void editRuStopWordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRuStopWordsButtonActionPerformed
        ruStopWordsFrame.setVisible(true);
        ruStopWordsFrame.setBounds(300, 200, 400, 300);
    }//GEN-LAST:event_editRuStopWordsButtonActionPerformed

    private void editEngStopWordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEngStopWordsButtonActionPerformed
        engStopWordsFrame.setVisible(true);
        engStopWordsFrame.setBounds(300, 200, 400, 300);
    }//GEN-LAST:event_editEngStopWordsButtonActionPerformed

Timer timer = new Timer(3000, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent evt) {
        loadingFrame.dispose();
    }
});    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FreqTable;
    private javax.swing.JFrame MainJFrame;
    private javax.swing.JMenuItem analyzeButton;
    private javax.swing.JMenuItem deleteSelectionsButton;
    private javax.swing.JLabel descriptionLabel1;
    private javax.swing.JLabel descriptionLabel2;
    private javax.swing.JLabel descriptionLabel3;
    private javax.swing.JMenuItem editEngStopWordsButton;
    private javax.swing.JMenuItem editRuStopWordsButton;
    private javax.swing.JFrame engStopWordsFrame;
    private javax.swing.JList<String> engStopWordsList;
    private javax.swing.JScrollPane engStopWordsScrollPanel;
    private javax.swing.JMenuItem exitButton;
    private javax.swing.JButton exitFromGuideButton;
    private javax.swing.JMenuItem exportButton;
    private javax.swing.JMenu extraSettingsMenu;
    private javax.swing.JLabel gifLabel;
    private javax.swing.ButtonGroup group;
    private javax.swing.JButton guideButton;
    private javax.swing.JDialog guideDialog;
    private javax.swing.JPanel guidePanel;
    private javax.swing.JLabel helloLabel1;
    private javax.swing.JLabel helloLabel2;
    private javax.swing.JMenuItem importButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JFrame loadingFrame;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel numberDelWordsField;
    private javax.swing.JLabel numberWordsField;
    private javax.swing.JButton okSaveReportButton;
    private javax.swing.JButton okUploadFileButton;
    private javax.swing.JButton okUploadStopWordsButton;
    private javax.swing.JLabel popularWordField;
    private javax.swing.JFrame ruStopWordsFrame;
    private javax.swing.JList<String> ruStopWordsList;
    private javax.swing.JScrollPane ruStopWordsScrollPanel;
    private javax.swing.JDialog saveReportMessage;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel unpopularWordField;
    private javax.swing.JDialog uploadFileMessage;
    private javax.swing.JDialog uploadStopWordsMessage;
    private javax.swing.JRadioButtonMenuItem useEngButton;
    private javax.swing.JCheckBoxMenuItem useEngStopWordsButton;
    private javax.swing.JCheckBoxMenuItem useRuStopWordsButton;
    private javax.swing.JRadioButtonMenuItem useRusButton;
    private javax.swing.JMenu useStopWords;
    // End of variables declaration//GEN-END:variables
}
